# the name of your track or event
name = "Data and IPFS: Models"

# the name of the group organizing the event
org = ""

# the github handle of the directly responsible individual for this event
# (this person will coordinate with devent organizers)
dri = "@aschmahmann"

# the website of the event
# make sure to have all the relevant information: dates, venue, program, ticketing (if any), etc.
website = ""

# the start date of the event
date = "2022-07-13"

# how many days the event lasts (1 - N)
days = 1

# the event times (shows up in the event card)
times = "13:00 - 17:00"

# the event venue name (will show up on the event card - TODO)
venueName = ""

# the event venue address (will show up on a map -- TODO)
venueAddress = ""

# the max number of attendees of the event
attendees = "50"

# these is unsued:
# tickets = "Waitlist"

# the "difficulty" of the event -- one of:
# ["Beginner", "Intermediate", "Advanced", "All Welcome"]
difficulty = "All Welcome"

# tags for the event, will show up as labels.
# pick 1-4
tags = ["Talks", "Workshops"]

# a color, to group key events visually. use sparingly
# color="purple"

# a description of the track.
# will show up when the user clicks the event card.
description = """

Part 1 of the "Data and IPFS" track will cover pain points stemming from the way data is structured within IPFS & IPLD

- Making UnixFS not special (e.g. rendering other types of files/folders on gateways)
- The relationships between Checksums, Blocks, etc.
- Compatibility with existing (and new) hash linked data structures
- Abstractions we have and want for working with hash linked data structures

People should come prepared with a prompt for "What's your vision for working with data in IPFS, and what about how it works today causes you the most pain?".
Write it up in https://pl-strflt.notion.site/Your-vision-for-IPFS-and-Data-15087c9885db48df8af4f11fc62d15e1. See the welcome discussion for slot for more info.

"""

# schedule is an array of timeslots objects
# schema:
#  startTime   - string for starting time
#  speakers    - array of string speaker names. please to use consistent naming across timeslots
#  title       - string for talk or timeslot title, should be short
#  description - string describing the timeslot. 1-3 sentences.
# 
# Notes:
# - recommended start: 09:00
# - recommended lunch: 12:00 or 13:00
# - recommended end:   17:00
# - use 15m, 20m, 30m, 45m, or 60m session slots
# - use 15m breaks, one in the morning, one or two in the afternoon
[[timeslots]]
startTime="13:00"
speakers=["@aschmahmann"]
title="Welcome standup discussion and track intro"
description="""
A track introduction and discussion to figure out:
1. Why each of us are here and the backgrounds/use cases motivating us
2. Introduce an overview of our shared problem space
3. Identify what we want to accomplish during the day

People should come prepared with a prompt for "What's your vision for working with data in IPFS, and what about how it works today causes you the most pain?".
Write it up in https://pl-strflt.notion.site/Your-vision-for-IPFS-and-Data-15087c9885db48df8af4f11fc62d15e1.
"""

[[timeslots]]
startTime="13:30"
speakers=["@aschmahmann"]
title="Dealing with block limits"
description="The 2MiB block limit is a major source of interoperability pain, why does it exist and how can we deal with it?"

[[timeslots]]
startTime="14:00"
speakers=["@RangerMauve"]
title="IPLD on gateways, and with URLs"
description="This talk will go over how IPLD could be exposed as a first class citizen in gateways and how we can represent links to data with URLs."

[[timeslots]]
startTime="14:30"
speakers=[]
title="Group Discussion: Abstractions for hash-linked data"
description="Within IPLD we have a variety of abstractions like codecs, schemas and ADLs. What do we have and what do we need?"

[[timeslots]]
startTime="15:15"
speakers=[]
title="Break"
description=""

[[timeslots]]
startTime="15:30"
speakers=["@aschmahmann"]
title="What's with the IPLD Data Model, and what happens when you try and represent it - WAC"
description="""
The WebAssembly Codec was designed to serialize and transport IPLD Data Model data for the purposes of building IPLD tooling in WASM.
This talk will describe today's IPLD Data Model as well as how WAC is used to represent it.
"""

[[timeslots]]
startTime="16:00"
speakers=[]
title="Group Discussion: UnixFS and what comes next?"
description="UnixFS has been an IPFS staple for a long time, but it doesn't solve all the use cases people have for describing filesystems. What changes do we want to make and how would we make them?"

[[timeslots]]
startTime="16:45"
speakers=[]
title="Recap and brainstorming"
description="We have an afternoon of open data modeling and transfer slots tomorrow, what areas are ripe for new or continuing discussion?"
